[workspace]
members = ["hello_world", "usb_serial", "rtic_blinky"]
resolver = "2"

[workspace.dependencies]
cortex-m = { version = "0.7.7", features = [
    "critical-section-single-core",
    "inline-asm",
] }
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
nrf52840-hal = "0.19.0"
rtic = { version = "2.0.1", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "2.0.0", features = ["nrf52840"] }
usb-device = "0.3.2"
usbd-serial = "0.2.2"
